### ISSUE TITLE
new version wont open

### ISSUE THREAD

**Issue by parastooporl** [kiraio-moe/LoveLive2D#9]
when I try to open it it wont open the last version would open tho Im on windows and I tryed every windows ver but non would open in the new version

**Comment by kiraio-moe** [comment]
Fixed in #10. Sorry for the error.
You can download the latest release now!

**Comment by parastooporl** [comment]
Uploading 2024-08-01 08-21-43.mp4…

I download the files again but they still wont work it wont open

**Comment by kiraio-moe** [comment]
> I download the files again but they still wont work it wont open

What is the error like? Can you describe it? Or screenshot/video so I can understand?
Have you installed the .NET SDK?

**Comment by parastooporl** [comment]
when you said net sdk I went and download the x64 version now it works!!! thank you so much again you are really a life saver Im just a kid who wants to learn live2d and in my country I cant buy the paid ver nor I have the money, again thank you so much!!

**Comment by kiraio-moe** [comment]
> when you said net sdk I went and download the x64 version now it works!!! thank you so much again you are really a life saver Im just a kid who wants to learn live2d and in my country I cant buy the paid ver nor I have the money, again thank you so much!!

Your welcome :) Glad it's work. Keep learning!
